### ISSUE TITLE
tests is a standalone package

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#156]
Shouldn't `tests` be under `remoteappmanager`?
Think distribution.

**Comment by stefanoborini** [comment]
yes and no. technically it would make sense to have it embedded in. In practice, you would not want to ship tests in a compiled egg.

If we do so, however, we need to change:

- the import paths
- the flake8 in tox
- exclude them from the documentation
- move the selenium tests in there as well.

**Comment by kitchoi** [comment]
> In practice, you would not want to ship tests in a compiled egg.

If we decide not to ship tests with the distribution, we can always exclude them in MANIFEST.ini
In fact it is nice to include tests in sdist, so we can run tox tests.

**Comment by kitchoi** [comment]
And it is by default shipped, https://docs.python.org/3/distutils/sourcedist.html#specifying-the-files-to-distribute :
> anything that looks like a test script: test/test*.py (currently, the Distutils don’t do anything with test scripts except include them in source distributions, but in the future there will be a standard for testing Python module distributions)

**Comment by itziakos** [comment]
Yes, It is advised that tests for python packages are placed inside the main package (for us this is `remoteappmanager`).  It makes the package friendlier for package managers and allows users to report on failures. 

While the necessary changes are not difficult they are disruptive so I suggest that this issue is address on 0.7.0
