### ISSUE TITLE
Documentation audit: API does not document __init__

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#190]
API is automatically generated by apidoc, however, that left a number of classes' init not to be documented.

Notably, `remoteappmanager.db.orm.AppAccounting` and `remoteappmanager.db.csv_db.CSVAccounting` are referred to by deployment and configuration in the documentation.  User needs to know how to initialise them.

The `__init__` documentation were manually added in this PR: https://github.com/simphony/simphony-remote/pull/147
but then automatically removed by `apidoc` again in this PR: https://github.com/simphony/simphony-remote/pull/189

**Comment by itziakos** [comment]
Based on my experience using `sphinx-apidoc` is not the best solution mainly because the resulting rst code is agly.

To have documentation that is actually readable one needs to do the following:

- Use sphinx-apidoc for each top level subcomponent to have a draft in separate directories
- Update index.rst as necessary.
- setup the right global autodoc parameters at conf.py.
- fine tune the generated api files as necessary
- commit the changes

This should be done before every release (The logic can be encapsulated in the documentation makefiles) 

- run sphinx-apidoc to generate stub rst for new modules 
- fine tune the generated api files as necessary

**Comment by itziakos** [comment]
I will pickup this issue so provide an example of how to deal with api documentation

**Comment by itziakos** [comment]
Actually  there is a better way using `sphinx-autogen`

**Comment by stefanoborini** [comment]
Documentation is now restored to working status, and the init methods are now correctly documented. Closing

**Comment by stefanoborini** [comment]
Particularly, see PR #194 #232 #233 and #234
