### ISSUE TITLE
Factor out `traitlets documenter` as a subpackage 

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#193]

**Comment by stefanoborini** [comment]
@itziakos package has been renamed to traitlet_documenter (for uniformity with trait_documenter) and put in a separate repo under simphony. Test have been ported from trait documenter but many of them fail (even after removing the obvious features not supported by traitlets). Needs additional investigation.

Any preference on how to do a release on pypi, so that we can mark it as a dependency here?

**Comment by itziakos** [comment]
> Test have been ported from trait documenter but many of them fail (even after removing the obvious features not supported by traitlets).

In general traitlets documenter renders the output differently than trait documenter so it is not unexpected that all the tests can be adapted to work. It would be better to just use the trait-documenter as inspiration and not as a copy template.

> Any preference on how to do a release on pypi, so that we can mark it as a dependency here?

For the moment we should add mention the dependency in the doc requirements file and mention the  the dependency in the README. Please note that this is a documentation dependency and does not need to be in the setup.py
