### ISSUE TITLE
Test failures on master

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#195]
it looks that current master is failing this is probably have to do with changes in the travis-ci environment.
https://travis-ci.org/simphony/simphony-remote/builds/148363244

**Comment by stefanoborini** [comment]
We've seen that occasionally. I thought it was due to slow timeout, but it still happens. It's due to selenium tests. I have no idea of the underlying reason (the tmp dir is correctly created and the profile is there). In fact, the error message is generally deceiving. When I checked the source code, it's actually due to a timeout in getting the browser up and running.

**Comment by itziakos** [comment]
It has been happening more and more lately and it is annoying when working on a PR

**Comment by itziakos** [comment]
I am having a look at it

**Comment by stefanoborini** [comment]
@itziakos I see this plagues your PR #194 as well. I leave it to you then, but please keep me updated on the motivation.

**Comment by stefanoborini** [comment]
@itziakos sorry but you are on vacation and I need this fixed now, as I have a bunch of PR failing due to this problem. Reassigning it.

**Comment by stefanoborini** [comment]
Problem is due to an unsigned firefox xpi webdriver.
