### ISSUE TITLE
Keyboard focus is not handed to iframe

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#347]
To reproduce: start a vnc application, then try to type in it. Mouse works, keyboard does not.
Any attempt to type in the iframe on a VNC fails. It seems we are not transferring focus to the iframe object.

Version post 1.0

**Comment by stefanoborini** [comment]
Known novnc issue https://github.com/novnc/noVNC/issues/506 but apparently it's not of trivial solution (at least I didn't get the expected result with the proposed workarounds). I did manage to transfer the focus by manually forcing ("#canvas").focus(), however it is lost as soon as I select another element outside the iframe.

I think I'll have to track the focus and default it to the open canvas when on the body element (default)

**Comment by nightwing** [comment]
@stefanoborini this is caused by preventDefault call at https://github.com/novnc/noVNC/blob/b56d97524807b125d047730331031ddd00f9c61f/core/input/devices.js#L251. It prevents iframe from being focused.
The workaround for this is to call window.focus similar to https://github.com/ajaxorg/ace/blob/v1.2.6/lib/ace/mouse/mouse_handler.js#L51-L56

**Comment by stefanoborini** [comment]
@nightwing thank you! I'll check that as soon as I am back on the project.

**Comment by stefanoborini** [comment]
Seems that the solution I used matches what was needed. Closing.
