### ISSUE TITLE
Better testing for `HomeHandler`

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-remote#5]
We need a better testing infra for tornado web handlers.

**Comment by stefanoborini** [comment]
I envision two possible testing strategies:

1. Using the tornado services.
2. Doing actual requests.

We will have to mock the external services though.

**Comment by stefanoborini** [comment]
We encounter a tornado bug when dealing with this issue. https://github.com/tornadoweb/tornado/issues/1573 

I'll try to work around it a bit, but seems hard to do so without hacking tornado itself.

**Comment by stefanoborini** [comment]
Ready in pull request #48, although I recommend that we expand this approach as we will need to test other handlers (e.g. the REST api handler, or new methods).

I suggest to

- introduce fully functional mock objects for all the services that we use, with a clear "mock infrastructure" that returns something sensible and functional.
- Introduce the Form object to factor out validation of form submissions, so that POST handling becomes a bit cleaner and we can focus on testing the Form object, instead of the handler.
