### ISSUE TITLE
tempdir cannot create parent directory (does not perform mkdir -p)

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-remote#53]
With the current configuration, the temporary directory cannot be created.

[E 2016-07-06 13:55:21.914 JupyterHub spawner:137] Failed to create temporary directory for sborini in /tmp/remoteapp
    Traceback (most recent call last):
      File "/Users/sborini/Work/github/simphony-remote/remoteappmanager/spawner.py", line 132, in start
        dir=self.workspace_dir)
      File "/Users/sborini/Work/github/simphony-remote/venv/lib/python3.4/tempfile.py", line 295, in mkdtemp
        _os.mkdir(file, 0o700)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/remoteapp/tmp_cgc50xi'

**Comment by kitchoi** [comment]
'/tmp/remoteapp' is defined in the remoteappmanager_config.py
It is the admin's responsibility to setup an existing directory right?

**Comment by stefanoborini** [comment]
True, but it's a bit harsh. We should make sure it's created anyway.

**Comment by kitchoi** [comment]
The flip side of being harsh is being safe.  Similar to docker creating a directory for you on the host machine when it is not available for mounting; that upsets some people.

**Comment by stefanoborini** [comment]
You can be harsh, but it should be clear what's wrong, possibly preemptively. At least we should add a check and be a bit more verbose (Please create...). The problem is that lack of this directory compromises the whole run, and introduces an additional step to deployment. You would like the experience to be as smooth as possible.

**Comment by kitchoi** [comment]
I would think that the error message is already quite clear what's wrong and the application continues to run. but I am also in favour of making the error message nicer

e.g. `/tmp/remoteapp does not exist.  Temporary workspace will not be available.  Please create /tmp/remoteapp or assign spawner's workspace_dir to an existing directory`.

Alternatively we can make set default `Spawner.workspace_dir = None` in `jupyterhub_config.py`, so that the application works "out-of-the-box".  I am however against this idea because an unaware admin may later realise that that the host machine's hard drive run out of space.

**Comment by kitchoi** [comment]
Ah correction on minor details:
>  we can set default Spawner.workspace_dir = None

Not `None`, but `tempfile.tempdir` (it depends on the platform)
