### ISSUE TITLE
remoteappdb's database should be an argument

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#86]
The path for the database is required in every command.  It makes sense that it is an argument rather than an option.

In addition, having `db` as an argument gives an added benefit of autocompletion by shell (e.g. bash).

**Comment by kitchoi** [comment]
Changing this would affect the API of the command-line tool (but only that) and would require amendment of the documentation on deployment and makefile.

**Comment by stefanoborini** [comment]
Doing so makes the interface a bit awkward in its readability, and I am not sure click allows us to put it before the group commands. We should always put it at the end.

The option was the best out-of-band way to pass the information. In general, you want to go into a directory and act on the default database name.

I'm not sure.

**Comment by kitchoi** [comment]
The default database name is a related issue.  IMHO I'd rather there isn't a default, i.e. I might forget to do `--db=some_other_path.db app create ...` and not noticing that I am modifying a default database that happens to exist.

As for the argument position, the argument would go before the group commands indeed, so you get 
```
remoteappdb DB COMMANDS...
```
For example, you would do
```
$ remoteappdb ~/remoteappmanager.db app create something
```

Right now having `db` as an option in the top most context also forces you to do
```
$ remoteappdb --db=path.db app create something
```
whilst the following throws you an error:
```
$ remoteappdb app create something --db=path.db
```

**Comment by kitchoi** [comment]
Correction, if `--db` is not provided, the default name is used, and if it does not exist, it is created, and that's weird for me, but it might just be me.

**Comment by stefanoborini** [comment]
I need to check if we can specify an argument at that level. Let me do some experiments with click.

**Comment by stefanoborini** [comment]
Ok, I just verified. We can indeed pass db as an argument, so that we will end up with requests like

```
remoteappdb foo.db init
remoteappdb foo.db app create foobar
```

It's not too complex, but I need @itziakos to prioritise it accordingly.

**Comment by itziakos** [comment]
# The way I understand it we have a `global` configuration option related to the db path. 
# I like the ability to support a default place
# I like the ability to support changing the path
# I do not like to have to write the custom path all the time

I am not in favor of having the `db` path as an argument. It make life a little more complicated
There are a number solutions to this

- Create an `alias` that will include the `--db` option and use that  (workaround)
- Support overriding the path with an Environment variable
- Support a configuration file for the cli tools

The ideal for me is a proper configuration file but we already have a good number of them. So for the moment I will keep this issue on hold (since we have a workaround). To consider on the generic UX of the IT person that will maintain the setup.

**Comment by stefanoborini** [comment]
Needs decision on strategy to put the configuration file (/etc ? )
